name = "plonky3-example"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CertiPlonk"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3
# linter.hashCommand = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "LeanZKCircuit_Plonky3"
path = "../LeanZKCircuit-Plonky3"

[[require]]
name = "Arklib"
path = "../ZKLib"

[[lean_lib]]
name = "CertiPlonk"
