name = "plonky3-example"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CertiPlonk"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3
# linter.hashCommand = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[require]]
name = "LeanZKCircuit_Plonky3"
git = "https://github.com/XC0R/LeanZKCircuit-Plonky3"
rev = "02a993a8c43ffd60206acf43730d86eb05ee909d"

[[require]]
name = "Arklib"
git = "https://github.com/XC0R/ArkLib"
rev = "b98d03e2e13e7efc28760dbdb4cf8aca6ce999b0"

[[lean_lib]]
name = "CertiPlonk"
