name = "plonky3-example"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CertiPlonk"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3
# linter.hashCommand = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "LeanZKCircuit_Plonky3"
git = "https://github.com/XC0R/LeanZKCircuit-Plonky3"
rev = "5f1eecc"

[[require]]
name = "Arklib"
git = "https://github.com/XC0R/ArkLib"
rev = "d2a7cd3d"

[[lean_lib]]
name = "CertiPlonk"
